server {
    listen 80;
    server_name _;

    port_in_redirect off;

    root /var/www/projets;
    index index.php index.html;

    location / {
        try_files $uri $uri/ $uri/index.html $uri/index.php =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}